### ISSUE TITLE
Serverless error attempting to delete `warmUpPlugin` function

### ISSUE THREAD

**Issue by JimD2L** [FidelLimited/serverless-plugin-warmup#12]
When using a custom name, I encountered a serverless error in my TravisCI build's deploy section.

Serverless was trying to remove/apply x-ray settings to a lambda with a `warmUpPlugin` suffix on the lambda ARN. I was able to work around this by manually creating a lambda with that name, but I believe this to be a bug.

Perhaps related to this line: https://github.com/FidelLimited/serverless-plugin-warmup/blob/master/src/index.js#L232

Warm up settings:
```
  warmup:
    memorySize: 128
    name: '${self:service}-${opt:stage}-lambda-warmup'
```

**Comment by goncaloneves** [comment]
@JimD2L the only way I think it could break is if your first CF deployment had one name (default) and then you deployed again with a different name. Is that what happened?

In order to do the change, you would need to first deploy without warmup and then again with warmup with a new name.

This issue can be fixed with a little change in that line making `warmUpPlugin` naming depend on the function name.

**Comment by JimD2L** [comment]
Yes, this was a case of adding warmup to an existing project that had already been deployed.

**Comment by goncaloneves** [comment]
@JimD2L That's not the issue. What I meant when deploying warmup a second time with a different name. The same goes with any other function.

**Comment by goncaloneves** [comment]
Closing this issue, because is non specific with Warmup plugin but a Cloudformation constraint.
