### ISSUE TITLE
Not running in set interval and no logs showing for invoked function

### ISSUE THREAD

**Issue by webchaz** [FidelLimited/serverless-plugin-warmup#133]
Hello,

I have warmup set globally in custom to run for all functions with the following:

```
custom:
  warmup:
    enabled: true
    events:
      schedule: rate(2 minutes)
```

This is actually only running every 5 minutes however according to the warm-up CloudWatch logs.  

Additionally, I can see it is showing `Warming up function my-function with concurrency: 1` and it shows that it invoked successfully.  However, when I check the logs for my function, it's not invoking it at all.  

I'm using `async` for my functions and have it setup as:

```
module.exports.test = async (event, context) => {
  context.callbackWaitsForEmptyEventLoop = false
  if (event.source === 'serverless-plugin-warmup') {
    await new Promise(r => setTimeout(r, 25))
    return true
  }
 //my code
}
```

Any idea why it's showing that it invoked the function successfully, but is showing no logs for the actual function?

**Comment by webchaz** [comment]
Ok, so it looks like even with a `sls deploy` it doesn't update the event schedule.   The second thing I noticed is that if using `context.callbackWaitsForEmptyEventLoop = false` it needs to be after the warmup call for whatever reason.  I just manually edited the event interval and changed the context position and all is good.

Not sure if the event schedule update is something you want to look into so I'll leave this open, otherwise can probably be closed.  Thanks!

**Comment by juanjoDiaz** [comment]
Hi @webchaz,

Let's see those one by one.

**The schedule property isn't set properly.**
Most likely because you are missing a dash `-`.
```js
custom:
  warmup:
    enabled: true
    events:
      - schedule: rate(2 minutes)
```
The dash is important in yaml since it differentiates arrays from objects.
Without that you are saying `{ events: { schedule: 'rate(2 minutes)' } }`.
With it you are saying `{ events: [ schedule: 'rate(2 minutes)' ] }`.

**It doesn't actually invoke the lambda.**
How do you know that?
You don't have any special log for the serverless call so how do you distinguish the warmup call from normal user calls?
If it prints `Warming up function my-function with concurrency: 1` it means that it has invoked the lambda and the lambda has responded sucessfully.
Which log are you looking at?
Keep in mind that the warmup calls the lambda directly so it won't show on the API Gateway logs. Only in the lambda logs.

*callbackWaitsForEmptyEventLoop needs to be false*
`context.callbackWaitsForEmptyEventLoop = false` is needed when you have unresolved promises, open connections (like the connection pools created by db drivers), etc.
So it shouldn't have anything to do with this pluging.


*Couple other comments*
`I just manually edited the event interval and changed the context position and all is good.`
What do you mean by changing the context?

You don't need to wait the 25 seconds unless your concurrency is higher than 1.
So you can replace:
```js
  if (event.source === 'serverless-plugin-warmup') {
    await new Promise(r => setTimeout(r, 25))
    return true
  }
```
by

```js
  if (event.source === 'serverless-plugin-warmup') {
    return true
  }
```

**Comment by webchaz** [comment]
Hi @juanjoDiaz,

Thanks for this explanation, with the `- schedule` it updates perfectly.

Regarding not invoking, it actually was invoking.  So, to start this is a function that is not being used in production or by anyone else, so when I check logs in CloudWatch, it's only my own invokes (or warmup).

I did see that it was in fact invoking the function from the warmup lambda, however for some reason with `context.callbackWaitsForEmptyEventLoop = false` above my warmup check, there were just no logs for the function being invoked.   My db connection is called below this (and cached locally), so perhaps that's why? not sure.  But as soon as I moved it below the warmup check, I was getting logs for my function in the expected intervals.

**Comment by juanjoDiaz** [comment]
Yeah. The `context.callbackWaitsForEmptyEventLoop = false` is most likely needed because of the db connection. If you haven't yet, you probably want to read a bit about how lambdas are "frozen" between invocations and why db connections must be initialized outside of the handler.

Closing this since the questions about this particular plugin were solved.
Feel free to reopen if needed
