### ISSUE TITLE
Is there any reason why all the releases are -rc.1?

### ISSUE THREAD

**Issue by juanjoDiaz** [FidelLimited/serverless-plugin-warmup#15]
Hi,

Is there any reason why all the releases are -rc.1?
What is the project missing to be a full release? tests? something else?

Cheers!

**Comment by goncaloneves** [comment]
Tests.

I have all these Serverless MIT projects as side quests right now. They have been working flawlessly in prod for us at Fidel but because we are very small team and close to public release I don't have the time luxury to do tests.

So that's why we have the rc, just as a disclaimer alert and possibly a way for people to help out.
