### ISSUE TITLE
Environment variable STAGE must contain string

### ISSUE THREAD

**Issue by EGrun** [FidelLimited/serverless-plugin-warmup#155]
As part of our build, we set the STAGE environment variable. After upgrading to version 4.5.3, we were getting this error during the 'serverless deploy':

```
Environment variable STAGE must contain string
```

Setting the environment variable in the warmup configuration settings allowed us to deploy:
```
  warmup:
    environment:
      STAGE: ${self:provider.stage}
```

**Comment by juanjoDiaz** [comment]
In which version were you before?

I know that there are some issues around the way that serverless resolves env variables and other configs to populate `provider`.

**Comment by EGrun** [comment]
It was 3.3.0
We are setting the STAGE variable in the provider environment settings. I'm not sure why, but I believe this is why it was being overwritten in the 4.5.3 version of serverless-plugin-warmup.

```
provider:
...
  stage: ${opt:stage, 'dev'}
...
  environment:
    STAGE: ${self:provider.stage}
```

**Comment by juanjoDiaz** [comment]
Hi @EGrun and sorry for the radio silence.
I've had some other priorities and, since you already found a workaround, this had been left a bit forgotten. But I'm looking at it now.

First of all, in your first message, you were setting the env variable on the warmup plugin, on the last one you set it on the provider. Why do you want to pass the STAGE as an environment variable to the warmup lambda? The plugin will detect the stage (from env variables, service provider or default), deploy there and warmup functions in that stage. But the environment variable is never used for anything.

I've tried to replicate the issue but haven't been able to. If you could create a small sample project that replicates the issue I could take a look at it.

**Comment by juanjoDiaz** [comment]
Closing since there wasn't a response and I could replicate the issue.
Feel free to reopen if needed.
