### ISSUE TITLE
runtime parameter within the warmUpPlugin function is hardcoded

### ISSUE THREAD

**Issue by CartierDiamonds** [FidelLimited/serverless-plugin-warmup#209]
The plugin currently will only work for applications with a runtime of nodejs12.x, this should be configurable to work with older versions of node such as nodejs10.x

**Comment by juanjoDiaz** [comment]
The plugin runs on nodejs12.x indeed.
Your lambdas can run in whichever runtime you want.
They don't have to be the same.
Is this causing you any error? If so, can you elaborate?

**Comment by CartierDiamonds** [comment]
yes my functions need to be nodejs10.x, the error i get is "Value nodejs12.x at 'runtime' failed to satisfy contraint: Member must satisfy enum value set: [java8, nodejs8.10, nodejs10.x, python2.7, python3.6... etc] we do not have nodejs12.x

**Comment by juanjoDiaz** [comment]
That error seems to come from the serverless framework because you are using an old version.
Updating your `serverless` dependency should fix the problem.

If you don't want to do that, you can use versión `4.7.1-rc.1` which still used node10.x.

There have been already some discussions about this and I still see no reason to allow customizable runtimes for the plugin.
