### ISSUE TITLE
Serverless.yml plugin order doesn't work

### ISSUE THREAD

**Issue by matteocannata** [FidelLimited/serverless-plugin-warmup#43]
I need to to apply the plugin after the serverless-plugin-typescript compiles my project, but that doesn't work, the warmup is always applied first, even if it's declared after in my serverless.yml
Problem is that typescript expects an index.ts file instead of index.js inside the _warmup folder

```
serverless.yml
...
plugins:          
  - serverless-plugin-typescript
  - serverless-plugin-warmup
```
I fix this adding a custom options `typescript: true` in the .yml file, then modifying the filePath to `index.ts` if option's true.

**Comment by HyperBrain** [comment]
Shouldn't this be fixed in the typescript plugin? It should not dictate that the warmup plugin has to emit a ts file. E.g. if you use the webpack plugin together with the warmup plugin it also works, even if you use typescript everywhere else.
Imo, having my sources as TS does not mean that all my dependencies and tools also have to be TS.
