### ISSUE TITLE
Lambda warmup not waming up the function properly

### ISSUE THREAD

**Issue by nenti** [FidelLimited/serverless-plugin-warmup#66]
I installed the warmup plugin to my project and just realized that it is not working properly.

The warmup-lambda is peroperly executing every 5 minutes:
![image](https://user-images.githubusercontent.com/463984/42160778-c4cde176-7df8-11e8-889b-fe00417aa22e.png)

The logs indicate a successful execution:
```
START RequestId: 3b04bd5d-7de1-11e8-8fdf-7b05371b3361 Version: $LATEST
2018-07-02T10:18:14.729Z	3b04bd5d-7de1-11e8-8fdf-7b05371b3361	Warm Up Start
2018-07-02T10:18:15.187Z	3b04bd5d-7de1-11e8-8fdf-7b05371b3361	Warm Up Invoke Success: glypo-dev-captureTransaction { StatusCode: 200, Payload: '"Lambda is warm!"' }
2018-07-02T10:18:15.187Z	3b04bd5d-7de1-11e8-8fdf-7b05371b3361	Warm Up Finished with 0 invoke errors
```

But the function monitoring on `captureTransaction` doesn't log an invocation:
![image](https://user-images.githubusercontent.com/463984/42160888-20708d8a-7df9-11e8-884b-457d4bf6ecb8.png)

Also the end to end test is still showing following load times on sequential execution:
```
Received: 4846
Received: 1537
Received: 1627
Received: 1580
```

**Comment by goncaloneves** [comment]
@nenti WarmUP invokes `$LATEST` Lambda alias which stores the Invocation metrics under your `$LATEST` Lambda Resource CloudWatch metric. That's why it doesn't show up on Lambda monitoring view.

You could just check by FunctionName Lambda metric and it will show up fine in CloudWatch.

And you could check your service warmed up functions CloudWatch logs which you can easily cross-check if they are invoked or not.

**Comment by goncaloneves** [comment]
Are you running multiple version containers?
WarmUP guarantees one $LATEST version container warmed up. We discussed what would be the best approach to implement it at scale with multiple instances running in parallel in discussion #24.

**Comment by nenti** [comment]
No I only run one version of lambda. But still warmup invocations are showing up in different monitoring and the lambda doesn't seem to be warm when I invoke it.

Invocation comes from another service and is called like so:
```js
      const params = {
        FunctionName: arn,
        InvocationType: async ? 'Event' : 'RequestResponse',
        Payload: typeof data === 'object' ? JSON.stringify(data) : data,
      }

      return this.lambda.invoke(params, (error, result) => {
        // do something
      })
```

**Comment by goncaloneves** [comment]
You are invoking without `Qualifier` parameter. It doesn't seem? Or it isn't? Check the logs of the functions you are warming up and confirm.

https://github.com/FidelLimited/serverless-plugin-warmup/blob/e1c6a9b1ef16260d9c7379efd15ea5ebec6b2a8e/src/index.js#L271

**Comment by nenti** [comment]
Yes I invoke without Qualifier. But it is not a recommended field in invoke. So shouldn't we be expecting people calling without Qualifier?

**Comment by goncaloneves** [comment]
It is fine without Qualifier, by default it sets to `$LATEST` per AWS documentation. The only difference is the CW metrics are different. Not an issue.

If you are finding issues with cold starts, lower the schedule interval. I set to run every 2 minutes since in most use cases without external invocations most lambdas go cold around 3 minutes.

**Comment by ywang9009gmail** [comment]
Hi, is there a way to keep a specific version of function warm instead of $LATEST? Thanks
